services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./site:/var/www/html
      - ./api:/var/www/html/api
      - ./db:/var/www/html/db
      - ./data:/var/www/html/data
    environment:
      DB_TYPE: sqlite
      DB_PATH: /var/www/html/data/camabox.db

volumes:
  db_data:
